on: [pull_request]
name: API Gateway Build
jobs:
  build_test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Code
        uses: actions/checkout@v2
      - name: Run Main File
        run: |
          cd gateway
          go run main.go